///
/// code 000 is refered as 1 here
///
import {baseColors} from './baseColors';

export const colors = {
  background: {
    default: baseColors.neutral['005'],
    neutral: baseColors.neutral['100'],
    fill: {
      primaryActive: baseColors.brand['400'],
      primaryInverse: baseColors.neutral['000'],
      primaryInverseTransparent: baseColors.transparency.gray['000'],
      primaryDisabled: baseColors.neutral['010'],
      primaryHover: baseColors.brand['500'],
      secondaryActive: baseColors.brand['700'],
      secondaryDisabled: baseColors.neutral['050'],
      secondaryHover: baseColors.brand['400'],
      tertiaryActive: baseColors.brand['300'],
      errorLowemphasis: baseColors.red['050'],
      errorHighemphasis: baseColors.red['200'],
      successLowemphasis: baseColors.green['000'],
      warningLowemphasis: baseColors.orange['000'],
      warningHighemphasis: baseColors.orange['080'],
      informationLowemphasis: baseColors.blue['050'],
    },
    surface: {
      primary: baseColors.neutral['000'],
      primaryInverse: baseColors.transparency.brand['080'],
      secondary: baseColors.neutral['005'],
      tertiary: baseColors.transparency.gray['015'],
    },
  },
  border: {
    primary: baseColors.neutral['040'],
    primaryInverse: baseColors.neutral['030'],
    primaryActive: baseColors.brand['400'],
    primaryActiveInversed: baseColors.neutral['000'],
    primaryDisabled: baseColors.neutral['020'],
    secondaryActive: baseColors.brand['700'],
    error: baseColors.red['200'],
    success: baseColors.green['080'],
    warning: baseColors.orange['080'],
    information: baseColors.blue['400'],
  },
  text: {
    primary: baseColors.brand['700'],
    primaryInverted: baseColors.neutral['000'],
    secondary: baseColors.neutral['080'],
    secondaryInverted: baseColors.neutral['005'],
    tertiary: baseColors.neutral['060'],
    tertiaryInverted: baseColors.neutral['020'],
    error: baseColors.red['200'],
    success: baseColors.green['080'],
    warning: baseColors.orange['080'],
    information: baseColors.blue['400'],
    primaryActive: baseColors.brand['400'],
    primaryShade02: baseColors.brand['200'],
    primaryActiveInverse: baseColors.neutral['000'],
    primaryHover: baseColors.brand['500'],
    primaryActiveOnFill: baseColors.neutral['000'],
    primaryDisabled: baseColors.neutral['050'],
    secondaryActive: baseColors.brand['700'],
    nearBlack: baseColors.neutral['096'],
  },
  icon: {
    default: baseColors.brand['400'],
    primaryActive: baseColors.tale['000'],
    primaryInverse: baseColors.black['000'],
    primaryHover: baseColors.brand['500'],
    primaryOnFill: baseColors.neutral['000'],
    secondary: baseColors.brand['700'],
    tertiary: baseColors.neutral['005'],
    disabled: baseColors.neutral['020'],
    disabledOnFill: baseColors.neutral['050'],
    error: baseColors.red['200'],
    success: baseColors.green['080'],
    warning: baseColors.orange['080'],
    information: baseColors.blue['400'],
  },
  divider: {
    default: baseColors.neutral['010'],
    strong: baseColors.neutral['020'],
  },
  shadow: {
    default: baseColors.transparency.gray['040'],
  },
  gradient: {
    light: baseColors.gradient['001'],
    blue: baseColors.gradient['002'],
    darkBlue: baseColors.gradient['003'],
    lightBlue: baseColors.gradient['004'],
    lightGray: baseColors.transparency.brand['040'],
  },
};