import {baseNumbers} from './baseNumbers';

export const numbers = {
  gap: {
    '-16': baseNumbers['-16'],
    '0': baseNumbers['0'],
    '2': baseNumbers['2'],
    '4': baseNumbers['4'],
    '6': baseNumbers['6'],
    '8': baseNumbers['8'],
    '10': baseNumbers['10'],
    '12': baseNumbers['12'],
    '14': baseNumbers['14'],
    '16': baseNumbers['16'],
    '20': baseNumbers['20'],
    '24': baseNumbers['24'],
    '32': baseNumbers['32'],
    '40': baseNumbers['40'],
    '48': baseNumbers['48'],
  },
  padding: {
    '0': baseNumbers['0'],
    '2': baseNumbers['2'],
    '4': baseNumbers['4'],
    '8': baseNumbers['8'],
    '10': baseNumbers['10'],
    '12': baseNumbers['12'],
    '16': baseNumbers['16'],
    '20': baseNumbers['20'],
    '22': baseNumbers['22'],
    '24': baseNumbers['24'],
    '32': baseNumbers['32'],
    '40': baseNumbers['40'],
    '48': baseNumbers['48'],
    '70': baseNumbers['70'],
  },
  margin: {
    '4': baseNumbers['4'],
    '5': baseNumbers['5'],
    '6': baseNumbers['6'],
    '8': baseNumbers['8'],
    '12': baseNumbers['12'],
    '14': baseNumbers['14'],
    '16': baseNumbers['16'],
    '19': baseNumbers['19'],
    '20': baseNumbers['20'],
    '24': baseNumbers['24'],
    '27': baseNumbers['27'],
    '28': baseNumbers['28'],
    '32': baseNumbers['32'],
    '40': baseNumbers['40'],
    '48': baseNumbers['48'],
  },
  credential: {
    width_xs: baseNumbers['80'],
    height_xs: baseNumbers['50'],
    width_md: baseNumbers['326'],
    height_md: baseNumbers['200'],
    width_lg: baseNumbers['358'],
    height_lg: baseNumbers['124'],
  },
  radius: {
    xxs: baseNumbers['4'],
    xs: baseNumbers['8'],
    small: baseNumbers['10'],
    medium: baseNumbers['12'],
    large: baseNumbers['16'],
    xlarge: baseNumbers['20'],
    full: baseNumbers['832'],
  },
};